-keepattributes Signature
-keepattributes *Annotation*
-keep class com.jnetai.thermal.** { *; }
-keep class com.google.mlkit.** { *; }
-keep class com.google.android.gms.vision.** { *; }
-dontwarn com.google.mlkit.**
